module.exports = {
  Sequelize: jest.fn().mockImplementation(() => ({
    authenticate: jest.fn().mockResolvedValue(undefined),
    sync: jest.fn().mockResolvedValue(undefined),
    getDialect: jest.fn().mockReturnValue('postgres'),
    getDatabaseName: jest.fn().mockReturnValue('test_db'),
    query: jest.fn().mockResolvedValue([]),
    transaction: jest.fn().mockResolvedValue({}),
    close: jest.fn().mockResolvedValue(undefined),
    define: jest.fn().mockReturnValue({}),
  })),
  DataTypes: {
    STRING: 'STRING',
    INTEGER: 'INTEGER',
    BOOLEAN: 'BOOLEAN',
    DATE: 'DATE',
    TEXT: 'TEXT',
    ENUM: 'ENUM',
    JSON: 'JSON',
    UUID: 'UUID',
    UUIDV4: 'UUIDV4',
  },
  Model: jest.fn(),
  Op: {
    eq: 'eq',
    ne: 'ne',
    gte: 'gte',
    gt: 'gt',
    lte: 'lte',
    lt: 'lt',
    like: 'like',
    iLike: 'iLike',
    in: 'in',
    notIn: 'notIn',
    and: 'and',
    or: 'or',
  },
};