import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Home, FileText, BarChart3, Settings, Menu, X, LogOut, Users, Image, BookOpen, } from 'lucide-react';
import { useAuthStore } from '../stores/authStore';
const SidebarLink = ({ to, icon: Icon, children, isActive }) => (_jsxs(Link, { to: to, className: `group flex items-center px-2 py-2 text-sm font-medium rounded-md transition-colors ${isActive
        ? 'bg-secondary-100 text-secondary-900'
        : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'}`, children: [_jsx(Icon, { className: `mr-3 flex-shrink-0 h-5 w-5 transition-colors ${isActive ? 'text-secondary-500' : 'text-gray-400 group-hover:text-gray-500'}` }), children] }));
export default function Layout({ children }) {
    const [sidebarOpen, setSidebarOpen] = useState(false);
    const location = useLocation();
    const { user, logout } = useAuthStore();
    const navigation = [
        { name: 'Dashboard', href: '/dashboard', icon: Home },
        { name: 'Content', href: '/content', icon: FileText },
        { name: 'Courses', href: '/courses', icon: BookOpen },
        { name: 'Media Library', href: '/media', icon: Image },
        { name: 'Analytics', href: '/analytics', icon: BarChart3 },
        { name: 'Settings', href: '/settings', icon: Settings },
    ];
    const handleLogout = () => {
        logout();
    };
    return (_jsxs("div", { className: "h-screen flex overflow-hidden bg-gray-100", children: [_jsxs("div", { className: `fixed inset-0 flex z-40 md:hidden ${sidebarOpen ? '' : 'hidden'}`, children: [_jsx("div", { className: "fixed inset-0 bg-gray-600 bg-opacity-75", onClick: () => setSidebarOpen(false) }), _jsxs("div", { className: "relative flex-1 flex flex-col max-w-xs w-full bg-white", children: [_jsx("div", { className: "absolute top-0 right-0 -mr-12 pt-2", children: _jsx("button", { className: "ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white", onClick: () => setSidebarOpen(false), children: _jsx(X, { className: "h-6 w-6 text-white" }) }) }), _jsxs("div", { className: "flex-1 h-0 pt-5 pb-4 overflow-y-auto", children: [_jsx("div", { className: "flex-shrink-0 flex items-center px-4", children: _jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "h-8 w-8 bg-secondary-600 rounded-lg flex items-center justify-center", children: _jsx("span", { className: "text-white font-bold text-sm", children: "UC" }) }), _jsx("span", { className: "ml-2 text-lg font-semibold text-gray-900", children: "UpCoach CMS" })] }) }), _jsx("nav", { className: "mt-5 px-2 space-y-1", children: navigation.map(item => (_jsx(SidebarLink, { to: item.href, icon: item.icon, isActive: location.pathname === item.href ||
                                                (item.href === '/dashboard' && location.pathname === '/'), children: item.name }, item.name))) })] }), _jsx("div", { className: "flex-shrink-0 flex border-t border-gray-200 p-4", children: _jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx("div", { className: "h-8 w-8 bg-gray-300 rounded-full flex items-center justify-center", children: _jsx(Users, { className: "h-4 w-4 text-gray-600" }) }) }), _jsxs("div", { className: "ml-3", children: [_jsx("p", { className: "text-sm font-medium text-gray-700", children: user?.name || 'User' }), _jsxs("button", { onClick: handleLogout, className: "text-xs text-gray-500 hover:text-gray-700 flex items-center", children: [_jsx(LogOut, { className: "h-3 w-3 mr-1" }), "Sign out"] })] })] }) })] })] }), _jsx("div", { className: "hidden md:flex md:flex-shrink-0", children: _jsx("div", { className: "flex flex-col w-64", children: _jsxs("div", { className: "flex flex-col h-0 flex-1 border-r border-gray-200 bg-white", children: [_jsxs("div", { className: "flex-1 flex flex-col pt-5 pb-4 overflow-y-auto", children: [_jsx("div", { className: "flex items-center flex-shrink-0 px-4", children: _jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "h-8 w-8 bg-secondary-600 rounded-lg flex items-center justify-center", children: _jsx("span", { className: "text-white font-bold text-sm", children: "UC" }) }), _jsx("span", { className: "ml-2 text-lg font-semibold text-gray-900", children: "UpCoach CMS" })] }) }), _jsx("nav", { className: "mt-5 flex-1 px-2 space-y-1", children: navigation.map(item => (_jsx(SidebarLink, { to: item.href, icon: item.icon, isActive: location.pathname === item.href ||
                                                (item.href === '/dashboard' && location.pathname === '/'), children: item.name }, item.name))) })] }), _jsx("div", { className: "flex-shrink-0 flex border-t border-gray-200 p-4", children: _jsxs("div", { className: "flex items-center w-full", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx("div", { className: "h-8 w-8 bg-gray-300 rounded-full flex items-center justify-center", children: _jsx(Users, { className: "h-4 w-4 text-gray-600" }) }) }), _jsxs("div", { className: "ml-3 flex-1", children: [_jsx("p", { className: "text-sm font-medium text-gray-700", children: user?.name || 'User' }), _jsxs("button", { onClick: handleLogout, className: "text-xs text-gray-500 hover:text-gray-700 flex items-center", children: [_jsx(LogOut, { className: "h-3 w-3 mr-1" }), "Sign out"] })] })] }) })] }) }) }), _jsxs("div", { className: "flex flex-col w-0 flex-1 overflow-hidden", children: [_jsx("div", { className: "md:hidden pl-1 pt-1 sm:pl-3 sm:pt-3", children: _jsx("button", { className: "ml-1 flex items-center justify-center h-12 w-12 rounded-md focus:outline-none focus:ring-2 focus:ring-inset focus:ring-secondary-500", onClick: () => setSidebarOpen(true), children: _jsx(Menu, { className: "h-6 w-6 text-gray-600" }) }) }), _jsx("main", { className: "flex-1 relative z-0 overflow-y-auto focus:outline-none", children: _jsx("div", { className: "py-6", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 md:px-8", children: children }) }) })] })] }));
}
//# sourceMappingURL=Layout.js.map