/**
 * Advanced Feature Definitions
 * Extended feature set for personalization and prediction models
 * @version 1.0.0
 */

import { FeatureDefinition } from '../FeatureStore';

/**
 * Advanced user behavior features
 */
export const userBehaviorFeatures: FeatureDefinition[] = [
  // Engagement intensity features
  {
    name: 'user_engagement_score',
    description: 'Composite engagement score (0-100) based on activity patterns',
    dataType: 'float',
    featureGroup: 'user_behavior',
    computationLogic: 'weighted_avg(sessions, logins, ai_chats, goal_updates)',
    tags: ['engagement', 'composite'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_session_consistency_7d',
    description: 'Std deviation of daily sessions over 7 days (lower = more consistent)',
    dataType: 'float',
    featureGroup: 'user_behavior',
    computationLogic: 'STDDEV(daily_sessions) WHERE date >= NOW() - 7 days',
    aggregation: 'stddev',
    windowSize: '7d',
    tags: ['engagement', 'consistency'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_peak_activity_hour',
    description: 'Hour of day with highest activity (0-23)',
    dataType: 'integer',
    featureGroup: 'user_behavior',
    computationLogic: 'MODE(HOUR(activity_timestamp))',
    tags: ['engagement', 'timing'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_weekend_activity_ratio',
    description: 'Ratio of weekend to weekday activity',
    dataType: 'float',
    featureGroup: 'user_behavior',
    computationLogic: 'COUNT(weekend_activities) / COUNT(weekday_activities)',
    tags: ['engagement', 'timing'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_mobile_vs_web_ratio',
    description: 'Ratio of mobile to web sessions',
    dataType: 'float',
    featureGroup: 'user_behavior',
    computationLogic: 'COUNT(mobile_sessions) / NULLIF(COUNT(web_sessions), 0)',
    tags: ['engagement', 'platform'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_feature_breadth_score',
    description: 'Number of distinct features used (normalized 0-1)',
    dataType: 'float',
    featureGroup: 'user_behavior',
    computationLogic: 'COUNT(DISTINCT feature_used) / total_features',
    tags: ['engagement', 'adoption'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_habit_streak_max',
    description: 'Maximum habit streak achieved',
    dataType: 'integer',
    featureGroup: 'user_behavior',
    computationLogic: 'MAX(habit_streak)',
    tags: ['habits', 'achievement'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_habit_completion_rate_7d',
    description: 'Habit completion rate over last 7 days',
    dataType: 'float',
    featureGroup: 'user_behavior',
    computationLogic: 'SUM(completed_habits) / SUM(target_habits) WHERE date >= NOW() - 7d',
    windowSize: '7d',
    tags: ['habits', 'completion'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_message_sentiment_avg',
    description: 'Average sentiment score of user messages (-1 to 1)',
    dataType: 'float',
    featureGroup: 'user_behavior',
    computationLogic: 'AVG(message_sentiment)',
    tags: ['sentiment', 'communication'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_response_latency_avg_hours',
    description: 'Average time to respond to coach messages in hours',
    dataType: 'float',
    featureGroup: 'user_behavior',
    computationLogic: 'AVG(response_time_hours)',
    tags: ['communication', 'responsiveness'],
    owner: 'ml-team',
    deprecated: false,
  },
];

/**
 * Advanced AI interaction features
 */
export const aiInteractionFeatures: FeatureDefinition[] = [
  {
    name: 'user_ai_satisfaction_score',
    description: 'Average AI response satisfaction rating (1-5)',
    dataType: 'float',
    featureGroup: 'user_ai',
    computationLogic: 'AVG(ai_rating)',
    tags: ['ai', 'satisfaction'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_ai_conversation_depth',
    description: 'Average messages per AI conversation',
    dataType: 'float',
    featureGroup: 'user_ai',
    computationLogic: 'AVG(messages_per_conversation)',
    tags: ['ai', 'engagement'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_ai_topic_diversity',
    description: 'Number of distinct AI conversation topics',
    dataType: 'integer',
    featureGroup: 'user_ai',
    computationLogic: 'COUNT(DISTINCT conversation_topic)',
    tags: ['ai', 'diversity'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_ai_followup_rate',
    description: 'Rate of AI suggestions followed up on',
    dataType: 'float',
    featureGroup: 'user_ai',
    computationLogic: 'SUM(suggestions_followed) / SUM(suggestions_given)',
    tags: ['ai', 'adoption'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_ai_preferred_mode',
    description: 'Preferred AI mode (0=text, 1=voice, 2=mixed)',
    dataType: 'integer',
    featureGroup: 'user_ai',
    computationLogic: 'MODE(ai_interaction_mode)',
    tags: ['ai', 'preference'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_hybrid_vs_cloud_ratio',
    description: 'Ratio of on-device to cloud AI usage',
    dataType: 'float',
    featureGroup: 'user_ai',
    computationLogic: 'COUNT(on_device_inference) / COUNT(cloud_inference)',
    tags: ['ai', 'infrastructure'],
    owner: 'ml-team',
    deprecated: false,
  },
];

/**
 * Churn prediction features
 */
export const churnPredictionFeatures: FeatureDefinition[] = [
  {
    name: 'user_churn_risk_score',
    description: 'Predicted churn probability (0-1)',
    dataType: 'float',
    featureGroup: 'user_churn',
    computationLogic: 'ml_model_prediction(churn_model)',
    tags: ['churn', 'prediction'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_engagement_trend_14d',
    description: 'Engagement trend over 14 days (positive = increasing)',
    dataType: 'float',
    featureGroup: 'user_churn',
    computationLogic: 'linear_regression_slope(daily_engagement, 14)',
    windowSize: '14d',
    tags: ['churn', 'trend'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_inactivity_periods_30d',
    description: 'Number of 3+ day inactivity periods in last 30 days',
    dataType: 'integer',
    featureGroup: 'user_churn',
    computationLogic: 'COUNT(inactivity_periods >= 3 days) WHERE date >= NOW() - 30d',
    windowSize: '30d',
    tags: ['churn', 'inactivity'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_support_tickets_30d',
    description: 'Number of support tickets in last 30 days',
    dataType: 'integer',
    featureGroup: 'user_churn',
    computationLogic: 'COUNT(support_tickets) WHERE date >= NOW() - 30d',
    windowSize: '30d',
    tags: ['churn', 'support'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_feature_usage_decline_rate',
    description: 'Rate of feature usage decline over time',
    dataType: 'float',
    featureGroup: 'user_churn',
    computationLogic: '(usage_week1 - usage_week4) / usage_week1',
    tags: ['churn', 'decline'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_billing_issue_flag',
    description: 'Whether user has billing issues (0 or 1)',
    dataType: 'boolean',
    featureGroup: 'user_churn',
    computationLogic: 'has_failed_payment OR has_expiring_card',
    tags: ['churn', 'billing'],
    owner: 'ml-team',
    deprecated: false,
  },
];

/**
 * Goal and progress features
 */
export const goalProgressFeatures: FeatureDefinition[] = [
  {
    name: 'user_active_goals_count',
    description: 'Number of active goals',
    dataType: 'integer',
    featureGroup: 'user_goals_advanced',
    computationLogic: 'COUNT(goals) WHERE status = active',
    tags: ['goals', 'count'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_goal_success_rate_all_time',
    description: 'All-time goal success rate',
    dataType: 'float',
    featureGroup: 'user_goals_advanced',
    computationLogic: 'SUM(completed_goals) / SUM(total_goals)',
    tags: ['goals', 'success'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_avg_goal_duration_days',
    description: 'Average number of days to complete a goal',
    dataType: 'float',
    featureGroup: 'user_goals_advanced',
    computationLogic: 'AVG(goal_completion_days)',
    tags: ['goals', 'duration'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_goal_update_frequency',
    description: 'Average goal updates per week',
    dataType: 'float',
    featureGroup: 'user_goals_advanced',
    computationLogic: 'COUNT(goal_updates) / weeks_active',
    tags: ['goals', 'engagement'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_goal_type_preference',
    description: 'Most common goal category (encoded)',
    dataType: 'integer',
    featureGroup: 'user_goals_advanced',
    computationLogic: 'MODE(goal_category_encoded)',
    tags: ['goals', 'preference'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'goal_at_risk_score',
    description: 'Probability goal will miss deadline (0-1)',
    dataType: 'float',
    featureGroup: 'goal_metrics_advanced',
    computationLogic: 'ml_model_prediction(goal_risk_model)',
    tags: ['goals', 'risk'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'goal_momentum_score',
    description: 'Current momentum based on recent progress velocity',
    dataType: 'float',
    featureGroup: 'goal_metrics_advanced',
    computationLogic: 'recent_velocity / expected_velocity',
    tags: ['goals', 'momentum'],
    owner: 'ml-team',
    deprecated: false,
  },
];

/**
 * Session and coaching features
 */
export const sessionCoachingFeatures: FeatureDefinition[] = [
  {
    name: 'session_topic_category',
    description: 'Primary topic category of session (encoded)',
    dataType: 'integer',
    featureGroup: 'session_content',
    computationLogic: 'topic_classifier(session_transcript)',
    tags: ['session', 'topic'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'session_sentiment_trajectory',
    description: 'Sentiment change during session (-1 to 1)',
    dataType: 'float',
    featureGroup: 'session_content',
    computationLogic: 'end_sentiment - start_sentiment',
    tags: ['session', 'sentiment'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'session_action_items_count',
    description: 'Number of action items generated',
    dataType: 'integer',
    featureGroup: 'session_content',
    computationLogic: 'COUNT(action_items)',
    tags: ['session', 'outcomes'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'session_client_talk_ratio',
    description: 'Ratio of client to coach speaking time',
    dataType: 'float',
    featureGroup: 'session_content',
    computationLogic: 'client_speaking_time / coach_speaking_time',
    tags: ['session', 'dynamics'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'coach_specialization_match',
    description: 'Match score between coach specialty and client needs (0-1)',
    dataType: 'float',
    featureGroup: 'coach_matching',
    computationLogic: 'cosine_similarity(coach_skills, client_needs)',
    tags: ['matching', 'specialization'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'coach_style_compatibility',
    description: 'Compatibility score between coach and client styles (0-1)',
    dataType: 'float',
    featureGroup: 'coach_matching',
    computationLogic: 'style_compatibility_model(coach_style, client_preference)',
    tags: ['matching', 'style'],
    owner: 'ml-team',
    deprecated: false,
  },
];

/**
 * Content personalization features
 */
export const contentPersonalizationFeatures: FeatureDefinition[] = [
  {
    name: 'user_content_preference_vector',
    description: '64-dim embedding of content preferences',
    dataType: 'embedding',
    featureGroup: 'user_personalization',
    computationLogic: 'content_interaction_encoder(interactions)',
    tags: ['personalization', 'embedding'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_learning_style',
    description: 'Preferred learning style (0=visual, 1=auditory, 2=kinesthetic, 3=reading)',
    dataType: 'integer',
    featureGroup: 'user_personalization',
    computationLogic: 'classify_learning_style(content_interactions)',
    tags: ['personalization', 'learning'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_content_complexity_preference',
    description: 'Preferred content complexity level (1-5)',
    dataType: 'float',
    featureGroup: 'user_personalization',
    computationLogic: 'AVG(completed_content_complexity)',
    tags: ['personalization', 'complexity'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_content_length_preference',
    description: 'Preferred content length in minutes',
    dataType: 'float',
    featureGroup: 'user_personalization',
    computationLogic: 'AVG(completed_content_duration)',
    tags: ['personalization', 'length'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_notification_response_rate',
    description: 'Rate of notification engagement',
    dataType: 'float',
    featureGroup: 'user_personalization',
    computationLogic: 'SUM(notification_clicks) / SUM(notifications_sent)',
    tags: ['personalization', 'notifications'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_optimal_notification_time',
    description: 'Hour of day with highest notification response',
    dataType: 'integer',
    featureGroup: 'user_personalization',
    computationLogic: 'ARGMAX(notification_response_rate_by_hour)',
    tags: ['personalization', 'timing'],
    owner: 'ml-team',
    deprecated: false,
  },
];

/**
 * Social and community features
 */
export const socialCommunityFeatures: FeatureDefinition[] = [
  {
    name: 'user_community_engagement_score',
    description: 'Composite community engagement score',
    dataType: 'float',
    featureGroup: 'user_social',
    computationLogic: 'weighted_avg(posts, comments, reactions, shares)',
    tags: ['social', 'engagement'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_forum_posts_30d',
    description: 'Number of forum posts in last 30 days',
    dataType: 'integer',
    featureGroup: 'user_social',
    computationLogic: 'COUNT(forum_posts) WHERE date >= NOW() - 30d',
    windowSize: '30d',
    tags: ['social', 'posting'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_helpful_votes_received',
    description: 'Total helpful votes received on contributions',
    dataType: 'integer',
    featureGroup: 'user_social',
    computationLogic: 'SUM(helpful_votes)',
    tags: ['social', 'reputation'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_network_size',
    description: 'Number of connections/followers',
    dataType: 'integer',
    featureGroup: 'user_social',
    computationLogic: 'COUNT(connections)',
    tags: ['social', 'network'],
    owner: 'ml-team',
    deprecated: false,
  },
  {
    name: 'user_challenge_participation_rate',
    description: 'Rate of challenge participation',
    dataType: 'float',
    featureGroup: 'user_social',
    computationLogic: 'SUM(challenges_joined) / SUM(challenges_available)',
    tags: ['social', 'challenges'],
    owner: 'ml-team',
    deprecated: false,
  },
];

/**
 * All advanced features combined
 */
export const allAdvancedFeatures: FeatureDefinition[] = [
  ...userBehaviorFeatures,
  ...aiInteractionFeatures,
  ...churnPredictionFeatures,
  ...goalProgressFeatures,
  ...sessionCoachingFeatures,
  ...contentPersonalizationFeatures,
  ...socialCommunityFeatures,
];

/**
 * Feature group configurations for advanced features
 */
export const advancedFeatureGroups = [
  {
    name: 'user_behavior',
    description: 'Advanced user behavior and engagement patterns',
    entityType: 'user' as const,
    features: userBehaviorFeatures.map(f => f.name),
    ttl: 3600,
    owner: 'ml-team',
  },
  {
    name: 'user_ai',
    description: 'AI interaction patterns and preferences',
    entityType: 'user' as const,
    features: aiInteractionFeatures.map(f => f.name),
    ttl: 3600,
    owner: 'ml-team',
  },
  {
    name: 'user_churn',
    description: 'Churn prediction and risk features',
    entityType: 'user' as const,
    features: churnPredictionFeatures.map(f => f.name),
    ttl: 86400,
    owner: 'ml-team',
  },
  {
    name: 'user_goals_advanced',
    description: 'Advanced goal tracking features',
    entityType: 'user' as const,
    features: goalProgressFeatures.filter(f => f.featureGroup === 'user_goals_advanced').map(f => f.name),
    ttl: 3600,
    owner: 'ml-team',
  },
  {
    name: 'session_content',
    description: 'Session content analysis features',
    entityType: 'session' as const,
    features: sessionCoachingFeatures.filter(f => f.featureGroup === 'session_content').map(f => f.name),
    ttl: 86400,
    owner: 'ml-team',
  },
  {
    name: 'user_personalization',
    description: 'Content personalization features',
    entityType: 'user' as const,
    features: contentPersonalizationFeatures.map(f => f.name),
    ttl: 86400,
    owner: 'ml-team',
  },
  {
    name: 'user_social',
    description: 'Social and community engagement features',
    entityType: 'user' as const,
    features: socialCommunityFeatures.map(f => f.name),
    ttl: 3600,
    owner: 'ml-team',
  },
];
