// Manual mock for AIController to prevent model imports during tests
const mockFn = async () => ({ success: true });

export const aiController = {
  getRecommendations: mockFn,
  getOptimalTiming: mockFn,
  getAdaptiveSchedule: mockFn,
  processMessage: mockFn,
  generateSmartResponse: mockFn,
  createLearningPath: mockFn,
  getLearningPaths: mockFn,
  trackLearningProgress: mockFn,
  getNextModule: mockFn,
  analyzeVoice: mockFn,
  getVoiceCoaching: mockFn,
  getVoiceInsights: mockFn,
  compareVoiceSessions: mockFn,
  getActiveInsights: mockFn,
  dismissInsight: mockFn,
  getInsightReport: mockFn,
  predictGoalCompletion: mockFn,
  getBehaviorPatterns: mockFn,
  getEngagementMetrics: mockFn,
  getPredictions: mockFn,
  getSuccessFactors: mockFn,
  getInterventionPlan: mockFn,
  getCoachingStrategy: mockFn,
  getPersonalizedContent: mockFn,
  updatePersonalization: mockFn,
  getPersonalizationPreferences: mockFn,
  hybridGenerate: mockFn,
  getRoutingDecision: mockFn,
  trackAnalyticsEvent: mockFn,
};
